"""update booking status enum 3

Revision ID: 1281d4d1d843
Revises: 682c58855e7c
Create Date: 2026-03-27 13:13:13.702340

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1281d4d1d843'
down_revision: Union[str, Sequence[str], None] = '682c58855e7c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.execute("ALTER TYPE booking_status ADD VALUE IF NOT EXISTS 'accepted';")
    op.execute("ALTER TYPE booking_status ADD VALUE IF NOT EXISTS 'rejected';")
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
