"""add confidence_level in user car issue table

Revision ID: 12bf303bc2b7
Revises: 25553a867d71
Create Date: 2026-03-27 09:58:04.720264

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '12bf303bc2b7'
down_revision: Union[str, Sequence[str], None] = '25553a867d71'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_car_issues', sa.Column('confidence_level', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_car_issues', 'confidence_level')
    # ### end Alembic commands ###
