"""update table mechanic data

Revision ID: 12c7881b039c
Revises: c2e3de07f70e
Create Date: 2026-05-05 10:50:40.832186

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '12c7881b039c'
down_revision: Union[str, Sequence[str], None] = 'c2e3de07f70e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.alter_column(
        'mechanic_data',
        'initial_charge',
        existing_type=sa.VARCHAR(),
        type_=sa.Numeric(10, 2),
        existing_nullable=True,
        postgresql_using="trim(initial_charge)::numeric"
    )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('mechanic_data', 'initial_charge',
               existing_type=sa.Numeric(precision=10, scale=2),
               type_=sa.VARCHAR(),
               existing_nullable=True)
    # ### end Alembic commands ###
