"""add_failed_processing_cancelled_disputed_to_payment_status

Revision ID: 15bea1ef4374
Revises: 3c4cad2925f4
Create Date: 2026-04-07 11:15:40.671217

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '15bea1ef4374'
down_revision: Union[str, Sequence[str], None] = '3c4cad2925f4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
