"""add enum to service book table

Revision ID: 1661908c8ca1
Revises: 6e0d6ad9ab9d
Create Date: 2026-03-25 12:26:02.041722

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1661908c8ca1'
down_revision: Union[str, Sequence[str], None] = '6e0d6ad9ab9d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

booking_status_enum = sa.Enum(
    "pending", "arrived", "inspecting", "canceled", "repairing", "completed", "paid",
    name="booking_status"
)

def upgrade() -> None:
    booking_status_enum.create(op.get_bind(), checkfirst=True)
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('car_booking_services', sa.Column('status', sa.Enum('pending', 'arrived', 'inspecting', 'canceled', 'repairing', 'completed', 'paid', name='booking_status'), server_default='pending', nullable=False))
    op.add_column('rating_data', sa.Column('given_to', sa.UUID(), nullable=False))
    op.add_column('rating_data', sa.Column('given_by', sa.UUID(), nullable=False))
    op.drop_constraint(op.f('rating_data_mechanic_id_fkey'), 'rating_data', type_='foreignkey')
    op.drop_constraint(op.f('rating_data_user_id_fkey'), 'rating_data', type_='foreignkey')
    op.create_foreign_key(None, 'rating_data', 'users', ['given_by'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'rating_data', 'users', ['given_to'], ['id'], ondelete='CASCADE')
    op.drop_column('rating_data', 'user_id')
    op.drop_column('rating_data', 'mechanic_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('rating_data', sa.Column('mechanic_id', sa.UUID(), autoincrement=False, nullable=False))
    op.add_column('rating_data', sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'rating_data', type_='foreignkey')
    op.drop_constraint(None, 'rating_data', type_='foreignkey')
    op.create_foreign_key(op.f('rating_data_user_id_fkey'), 'rating_data', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('rating_data_mechanic_id_fkey'), 'rating_data', 'users', ['mechanic_id'], ['id'], ondelete='CASCADE')
    op.drop_column('rating_data', 'given_by')
    op.drop_column('rating_data', 'given_to')
    op.drop_column('car_booking_services', 'status')
    # ### end Alembic commands ###
