"""add index user_id and created at in user authentication

Revision ID: 1f1bce5e6678
Revises: 13f7b1e60316
Create Date: 2026-03-09 14:43:38.546305

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1f1bce5e6678'
down_revision: Union[str, Sequence[str], None] = '13f7b1e60316'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('idx_user_auth_user_created', 'user_authentications', ['user_id', 'created_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_user_auth_user_created', table_name='user_authentications')
    # ### end Alembic commands ###
