"""create mechanic image data table

Revision ID: 216cb03f0e24
Revises: d4b0c664be35
Create Date: 2026-04-01 11:01:29.094330

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '216cb03f0e24'
down_revision: Union[str, Sequence[str], None] = 'd4b0c664be35'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # 1. Convert type but keep nullable temporarily
    op.alter_column(
        'mechanic_image_data',
        'is_linked',
        existing_type=sa.VARCHAR(),
        type_=sa.Boolean(),
        nullable=True,
        postgresql_using="is_linked::boolean"
    )

    # 2. Replace NULL values
    op.execute(
        "UPDATE mechanic_image_data SET is_linked = false WHERE is_linked IS NULL"
    )

    # 3. Enforce NOT NULL
    op.alter_column(
        'mechanic_image_data',
        'is_linked',
        existing_type=sa.Boolean(),
        nullable=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('mechanic_image_data', 'is_linked',
               existing_type=sa.Boolean(),
               type_=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###
