"""create mechani stripe table

Revision ID: 30e93f97dc18
Revises: f6b62c6a22b8
Create Date: 2026-04-10 10:23:58.166372

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '30e93f97dc18'
down_revision: Union[str, Sequence[str], None] = 'f6b62c6a22b8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mechanic_stripes',
    sa.Column('mechanic_id', sa.UUID(), nullable=False),
    sa.Column('stripe_account_id', sa.String(), nullable=True),
    sa.Column('stripe_onboarded', sa.Boolean(), nullable=False),
    sa.Column('stripe_charges_enabled', sa.Boolean(), nullable=False),
    sa.Column('stripe_payouts_enabled', sa.Boolean(), nullable=False),
    sa.Column('last_transfer_id', sa.String(), nullable=True),
    sa.Column('last_transfer_amount', sa.Integer(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['mechanic_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('mechanic_id')
    )
    op.create_index(op.f('ix_mechanic_stripes_id'), 'mechanic_stripes', ['id'], unique=True)
    op.drop_column('users', 'stripe_account_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('stripe_account_id', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_mechanic_stripes_id'), table_name='mechanic_stripes')
    op.drop_table('mechanic_stripes')
    # ### end Alembic commands ###
