"""create customer car issue table and relationship

Revision ID: 3cf7c4dd8ac5
Revises: 3ff15cba96a5
Create Date: 2026-03-17 10:54:30.777726

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3cf7c4dd8ac5'
down_revision: Union[str, Sequence[str], None] = '3ff15cba96a5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
