"""add field certificates and remove certificate image field

Revision ID: 3ff15cba96a5
Revises: b13f70ad1d4b
Create Date: 2026-03-17 09:15:04.993496

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3ff15cba96a5'
down_revision: Union[str, Sequence[str], None] = 'b13f70ad1d4b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
