"""create mechanic image data table

Revision ID: 404021b5c99f
Revises: db6dc5a7fb93
Create Date: 2026-04-01 08:40:39.591301

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '404021b5c99f'
down_revision: Union[str, Sequence[str], None] = 'db6dc5a7fb93'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('mechanic_data', 'image_data_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.add_column('mechanic_image_data', sa.Column('is_linked', sa.String(), nullable=True))
    op.add_column('user_car_images', sa.Column('is_linked', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_car_images', 'is_linked')
    op.drop_column('mechanic_image_data', 'is_linked')
    op.alter_column('mechanic_data', 'image_data_id',
               existing_type=sa.UUID(),
               nullable=False)
    # ### end Alembic commands ###
