"""create mechanic_data table

Revision ID: 44bf9f4aaf04
Revises: 4ca4e91aa058
Create Date: 2026-03-15 15:16:41.234897

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '44bf9f4aaf04'
down_revision: Union[str, Sequence[str], None] = '4ca4e91aa058'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mechanic_data',
    sa.Column('shop_name', sa.String(), nullable=True),
    sa.Column('initial_charge', sa.String(), nullable=True),
    sa.Column('year_of_experience', sa.String(), nullable=True),
    sa.Column('service_area', sa.String(), nullable=True),
    sa.Column('specialist', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('national_id', sa.String(), nullable=True),
    sa.Column('national_id_image_url', sa.String(), nullable=True),
    sa.Column('certificate_image_url', sa.String(), nullable=True),
    sa.Column('certificate_id', sa.String(), nullable=True),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_index(op.f('ix_mechanic_data_id'), 'mechanic_data', ['id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_mechanic_data_id'), table_name='mechanic_data')
    op.drop_table('mechanic_data')
    # ### end Alembic commands ###
