"""create mechanic image data table

Revision ID: 468d17986e30
Revises: 8122c11e8fd9
Create Date: 2026-03-31 11:03:11.286254

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '468d17986e30'
down_revision: Union[str, Sequence[str], None] = '8122c11e8fd9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mechanic_image_data',
    sa.Column('national_image_id', sa.String(), nullable=True),
    sa.Column('national_id_image_url', sa.String(), nullable=True),
    sa.Column('certificates', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_mechanic_image_data_id'), 'mechanic_image_data', ['id'], unique=True)
    op.add_column('mechanic_data', sa.Column('image_data_id', sa.UUID(), nullable=False))
    op.create_foreign_key(None, 'mechanic_data', 'mechanic_image_data', ['image_data_id'], ['id'], ondelete='CASCADE')
    op.drop_column('mechanic_data', 'national_image_id')
    op.drop_column('mechanic_data', 'national_id_image_url')
    op.drop_column('mechanic_data', 'certificates')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('mechanic_data', sa.Column('certificates', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('mechanic_data', sa.Column('national_id_image_url', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('mechanic_data', sa.Column('national_image_id', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'mechanic_data', type_='foreignkey')
    op.drop_column('mechanic_data', 'image_data_id')
    op.drop_index(op.f('ix_mechanic_image_data_id'), table_name='mechanic_image_data')
    op.drop_table('mechanic_image_data')
    # ### end Alembic commands ###
