"""change latitude longitude to float

Revision ID: 4ca4e91aa058
Revises: e0990d4da3e0
Create Date: 2026-03-15 13:52:19.587540

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4ca4e91aa058'
down_revision: Union[str, Sequence[str], None] = 'e0990d4da3e0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.alter_column(
        'user_locations',
        'latitude',
        existing_type=sa.VARCHAR(),
        type_=sa.Float(),
        postgresql_using="latitude::double precision",
        existing_nullable=True
    )

    op.alter_column(
        'user_locations',
        'longitude',
        existing_type=sa.VARCHAR(),
        type_=sa.Float(),
        postgresql_using="longitude::double precision",
        existing_nullable=True
    )

def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user_locations', 'longitude',
               existing_type=sa.Float(),
               type_=sa.VARCHAR(),
               existing_nullable=True)
    op.alter_column('user_locations', 'latitude',
               existing_type=sa.Float(),
               type_=sa.VARCHAR(),
               existing_nullable=True)
    # ### end Alembic commands ###
