"""remove field tokens

Revision ID: 6451bd051ed4
Revises: a274c393e773
Create Date: 2026-03-07 10:28:45.605158

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6451bd051ed4'
down_revision: Union[str, Sequence[str], None] = 'a274c393e773'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_authentications', 'tokens')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_authentications', sa.Column('tokens', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
