"""add cascade

Revision ID: 73050cc44409
Revises: 4cf718ea1e7d
Create Date: 2026-03-07 12:45:06.881667

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '73050cc44409'
down_revision: Union[str, Sequence[str], None] = '4cf718ea1e7d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('user_authentications_user_id_fkey'), 'user_authentications', type_='foreignkey')
    op.create_foreign_key(None, 'user_authentications', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('user_profiles_user_id_fkey'), 'user_profiles', type_='foreignkey')
    op.create_foreign_key(None, 'user_profiles', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user_profiles', type_='foreignkey')
    op.create_foreign_key(op.f('user_profiles_user_id_fkey'), 'user_profiles', 'users', ['user_id'], ['id'])
    op.drop_constraint(None, 'user_authentications', type_='foreignkey')
    op.create_foreign_key(op.f('user_authentications_user_id_fkey'), 'user_authentications', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###
