"""create user car  image data table

Revision ID: 739f7cda3e79
Revises: a1e98fb85e6f
Create Date: 2026-03-31 12:11:26.361341

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '739f7cda3e79'
down_revision: Union[str, Sequence[str], None] = 'a1e98fb85e6f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('service_price_details_booking_id_fkey'), 'service_price_details', type_='foreignkey')
    op.create_foreign_key(None, 'service_price_details', 'car_booking_services', ['booking_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'service_price_details', type_='foreignkey')
    op.create_foreign_key(op.f('service_price_details_booking_id_fkey'), 'service_price_details', 'car_booking_services', ['booking_id'], ['id'])
    # ### end Alembic commands ###
