"""update user car issue table

Revision ID: 7bceb7bf716b
Revises: 3c335f15e396
Create Date: 2026-03-24 08:29:46.285148

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '7bceb7bf716b'
down_revision: Union[str, Sequence[str], None] = '3c335f15e396'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_car_issues', sa.Column('service_time', sa.Time(), nullable=True))
    op.alter_column('user_car_issues', 'service_date',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.Date(),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user_car_issues', 'service_date',
               existing_type=sa.Date(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=True)
    op.drop_column('user_car_issues', 'service_time')
    # ### end Alembic commands ###
