"""make sting to number in mechanic data table

Revision ID: 7d0a432d8b43
Revises: 44bf9f4aaf04
Create Date: 2026-03-17 08:20:39.960130

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7d0a432d8b43'
down_revision: Union[str, Sequence[str], None] = '44bf9f4aaf04'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('mechanic_data', 'year_of_experience',
            existing_type=sa.VARCHAR(),
            type_=sa.Integer(),
            existing_nullable=True,   postgresql_using="year_of_experience::integer")
         
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('mechanic_data', 'year_of_experience',
               existing_type=sa.Integer(),
               type_=sa.VARCHAR(),
               existing_nullable=True)
    # ### end Alembic commands ###
