"""re create user rating table and average rating table

Revision ID: 7d86d3f442f5
Revises: c06e268f7409
Create Date: 2026-03-25 09:33:05.851605

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '7d86d3f442f5'
down_revision: Union[str, Sequence[str], None] = 'c06e268f7409'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('avarage_rating',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('avg_rating', sa.Float(), nullable=False),
    sa.Column('total_rating', sa.Integer(), nullable=False),
    sa.Column('user_type', postgresql.ENUM('admin', 'customer', 'mechanic', name='user_type'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_index(op.f('ix_avarage_rating_id'), 'avarage_rating', ['id'], unique=True)
    op.create_table('rating_data',
    sa.Column('mechanic_id', sa.UUID(), nullable=False),
    sa.Column('rating', sa.Float(), nullable=False),
    sa.Column('review', sa.String(), nullable=True),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('rating_by', postgresql.ENUM('admin', 'customer', 'mechanic', name='rating_by'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['mechanic_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_rating_data_id'), 'rating_data', ['id'], unique=True)
    op.drop_index(op.f('ix_mechanic_ratings_id'), table_name='mechanic_ratings')
    op.drop_table('mechanic_ratings')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mechanic_ratings',
    sa.Column('mechanic_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('rating', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('review', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['mechanic_id'], ['users.id'], name=op.f('mechanic_ratings_mechanic_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('mechanic_ratings_user_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('mechanic_ratings_pkey'))
    )
    op.create_index(op.f('ix_mechanic_ratings_id'), 'mechanic_ratings', ['id'], unique=True)
    op.drop_index(op.f('ix_rating_data_id'), table_name='rating_data')
    op.drop_table('rating_data')
    op.drop_index(op.f('ix_avarage_rating_id'), table_name='avarage_rating')
    op.drop_table('avarage_rating')
    # ### end Alembic commands ###
