"""update payment status emun

Revision ID: 858c3d8d5ad1
Revises: a7f5d26b7b39
Create Date: 2026-04-10 12:17:39.603743

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '858c3d8d5ad1'
down_revision: Union[str, Sequence[str], None] = 'a7f5d26b7b39'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
