"""add relation in user with user_auth table

Revision ID: 912b3f90a8ed
Revises: b5243efa1ea2
Create Date: 2026-03-07 11:56:24.539982

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '912b3f90a8ed'
down_revision: Union[str, Sequence[str], None] = 'b5243efa1ea2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
