"""create user car  image data table

Revision ID: a1e98fb85e6f
Revises: 468d17986e30
Create Date: 2026-03-31 12:07:17.679271

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a1e98fb85e6f'
down_revision: Union[str, Sequence[str], None] = '468d17986e30'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_car_images',
    sa.Column('image_url', sa.String(), nullable=False),
    sa.Column('image_id', sa.String(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_car_images_id'), 'user_car_images', ['id'], unique=True)
    op.add_column('user_cars', sa.Column('car_image_id', sa.UUID(), nullable=False))
    op.create_foreign_key(None, 'user_cars', 'user_car_images', ['car_image_id'], ['id'], ondelete='CASCADE')
    op.drop_column('user_cars', 'image_url')
    op.drop_column('user_cars', 'image_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_cars', sa.Column('image_id', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('user_cars', sa.Column('image_url', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'user_cars', type_='foreignkey')
    op.drop_column('user_cars', 'car_image_id')
    op.drop_index(op.f('ix_user_car_images_id'), table_name='user_car_images')
    op.drop_table('user_car_images')
    # ### end Alembic commands ###
