"""add test field tokens to test

Revision ID: a274c393e773
Revises: c74f9304a28d
Create Date: 2026-03-07 10:28:12.692532

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a274c393e773'
down_revision: Union[str, Sequence[str], None] = 'c74f9304a28d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_authentications', sa.Column('tokens', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_authentications', 'tokens')
    # ### end Alembic commands ###
