"""create CarBookingService table

Revision ID: aad533c30fdc
Revises: 45d8252d058a
Create Date: 2026-03-24 13:43:57.222761

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'aad533c30fdc'
down_revision: Union[str, Sequence[str], None] = '45d8252d058a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('car_booking_services', sa.Column('booked_by', sa.UUID(), nullable=False))
    op.create_foreign_key(None, 'car_booking_services', 'users', ['booked_by'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'car_booking_services', type_='foreignkey')
    op.drop_column('car_booking_services', 'booked_by')
    # ### end Alembic commands ###
