"""create CarBookingService table

Revision ID: ae9f1d95c289
Revises: c121c41ecc56
Create Date: 2026-03-24 12:19:27.499874

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ae9f1d95c289'
down_revision: Union[str, Sequence[str], None] = 'c121c41ecc56'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('car_booking_services',
    sa.Column('user_car_issue_id', sa.UUID(), nullable=False),
    sa.Column('mechanic_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['mechanic_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_car_issue_id'], ['user_car_issues.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_car_booking_services_id'), 'car_booking_services', ['id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_car_booking_services_id'), table_name='car_booking_services')
    op.drop_table('car_booking_services')
    # ### end Alembic commands ###
