"""change field name in mechanic dat

Revision ID: b13f70ad1d4b
Revises: e761d697986e
Create Date: 2026-03-17 09:14:22.263099

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b13f70ad1d4b'
down_revision: Union[str, Sequence[str], None] = 'e761d697986e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('mechanic_data', sa.Column('certificates', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.drop_column('mechanic_data', 'certificate_image_id')
    op.drop_column('mechanic_data', 'certificate_image_url')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('mechanic_data', sa.Column('certificate_image_url', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('mechanic_data', sa.Column('certificate_image_id', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('mechanic_data', 'certificates')
    # ### end Alembic commands ###
