"""create new table user_authentication

Revision ID: c74f9304a28d
Revises: 9777d118ee9f
Create Date: 2026-03-07 10:15:23.176238

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c74f9304a28d'
down_revision: Union[str, Sequence[str], None] = '9777d118ee9f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_authentications',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('code', sa.String(), nullable=True),
    sa.Column('token', sa.String(), nullable=True),
    sa.Column('expire_time', sa.DateTime(), nullable=True),
    sa.Column('status', sa.Enum('pending', 'success', 'expire', name='auth_status'), server_default='pending', nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_authentications_id'), 'user_authentications', ['id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_authentications_id'), table_name='user_authentications')
    op.drop_table('user_authentications')
    # ### end Alembic commands ###
