"""add uniqe in Car booking service table

Revision ID: c8ba98f83b99
Revises: 6692efa8e02f
Create Date: 2026-04-03 14:36:31.841068

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c8ba98f83b99'
down_revision: Union[str, Sequence[str], None] = '6692efa8e02f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'car_booking_services', ['user_car_issue_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'car_booking_services', type_='unique')
    # ### end Alembic commands ###
