"""create mechanic image data table

Revision ID: d4b0c664be35
Revises: 404021b5c99f
Create Date: 2026-04-01 10:53:39.034398

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd4b0c664be35'
down_revision: Union[str, Sequence[str], None] = '404021b5c99f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.drop_constraint(
        op.f('mechanic_data_image_data_id_fkey'),
        'mechanic_data',
        type_='foreignkey'
    )

    op.drop_column('mechanic_data', 'image_data_id')

    op.alter_column(
        'user_car_images',
        'is_linked',
        existing_type=sa.VARCHAR(),
        type_=sa.Boolean(),
        nullable=False,
        postgresql_using="is_linked::boolean"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user_car_images', 'is_linked',
               existing_type=sa.Boolean(),
               type_=sa.VARCHAR(),
               nullable=True)
    op.add_column('mechanic_data', sa.Column('image_data_id', sa.UUID(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('mechanic_data_image_data_id_fkey'), 'mechanic_data', 'mechanic_image_data', ['image_data_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###
