"""create user car  image data table

Revision ID: db6dc5a7fb93
Revises: f33025147671
Create Date: 2026-03-31 12:53:53.612049

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'db6dc5a7fb93'
down_revision: Union[str, Sequence[str], None] = 'f33025147671'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('mechanic_image_data', sa.Column('user_id', sa.UUID(), nullable=False))
    op.create_foreign_key(None, 'mechanic_image_data', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.add_column('user_car_images', sa.Column('user_id', sa.UUID(), nullable=False))
    op.create_foreign_key(None, 'user_car_images', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user_car_images', type_='foreignkey')
    op.drop_column('user_car_images', 'user_id')
    op.drop_constraint(None, 'mechanic_image_data', type_='foreignkey')
    op.drop_column('mechanic_image_data', 'user_id')
    # ### end Alembic commands ###
