"""update user car issue table

Revision ID: e0135c1b50c7
Revises: 7bceb7bf716b
Create Date: 2026-03-24 08:52:06.124931

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e0135c1b50c7'
down_revision: Union[str, Sequence[str], None] = '7bceb7bf716b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_car_issues', sa.Column('latitude', sa.Float(), nullable=True))
    op.add_column('user_car_issues', sa.Column('longitude', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_car_issues', 'longitude')
    op.drop_column('user_car_issues', 'latitude')
    # ### end Alembic commands ###
