"""create user_car_issue and car_issue_data table

Revision ID: e0623646dbdb
Revises: 0eaded91be1f
Create Date: 2026-03-23 14:41:42.492126

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e0623646dbdb'
down_revision: Union[str, Sequence[str], None] = '0eaded91be1f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('car_issue_data',
    sa.Column('audio_files', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('image_files', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('user_car_issue_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_car_issue_id'], ['user_car_issues.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_car_issue_data_id'), 'car_issue_data', ['id'], unique=True)
    op.add_column('user_car_issues', sa.Column('summary', sa.String(), nullable=True))
    op.add_column('user_car_issues', sa.Column('issue', sa.String(), nullable=True))
    op.add_column('user_car_issues', sa.Column('severity_level', sa.String(), nullable=True))
    op.add_column('user_car_issues', sa.Column('car_id', sa.UUID(), nullable=False))
    op.alter_column('user_car_issues', 'service_date',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               nullable=True)
    op.drop_constraint(op.f('user_car_issues_user_id_key'), 'user_car_issues', type_='unique')
    op.create_foreign_key(None, 'user_car_issues', 'user_cars', ['car_id'], ['id'], ondelete='CASCADE')
    op.drop_column('user_car_issues', 'audio_text')
    op.drop_column('user_car_issues', 'image_analysis_text')
    op.drop_column('user_car_issues', 'description')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_car_issues', sa.Column('description', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('user_car_issues', sa.Column('image_analysis_text', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('user_car_issues', sa.Column('audio_text', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'user_car_issues', type_='foreignkey')
    op.create_unique_constraint(op.f('user_car_issues_user_id_key'), 'user_car_issues', ['user_id'], postgresql_nulls_not_distinct=False)
    op.alter_column('user_car_issues', 'service_date',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               nullable=False)
    op.drop_column('user_car_issues', 'car_id')
    op.drop_column('user_car_issues', 'severity_level')
    op.drop_column('user_car_issues', 'issue')
    op.drop_column('user_car_issues', 'summary')
    op.drop_index(op.f('ix_car_issue_data_id'), table_name='car_issue_data')
    op.drop_table('car_issue_data')
    # ### end Alembic commands ###
