"""create payment table and notification table

Revision ID: e06fee2cb232
Revises: c980269d74cb
Create Date: 2026-04-07 09:37:00.008242

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e06fee2cb232'
down_revision: Union[str, Sequence[str], None] = 'c980269d74cb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('payments', sa.Column('customer_id', sa.UUID(), nullable=False))
    op.drop_constraint(op.f('payments_booked_by_fkey'), 'payments', type_='foreignkey')
    op.create_foreign_key(None, 'payments', 'users', ['customer_id'], ['id'], ondelete='CASCADE')
    op.drop_column('payments', 'booked_by')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('payments', sa.Column('booked_by', sa.UUID(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'payments', type_='foreignkey')
    op.create_foreign_key(op.f('payments_booked_by_fkey'), 'payments', 'users', ['booked_by'], ['id'], ondelete='CASCADE')
    op.drop_column('payments', 'customer_id')
    # ### end Alembic commands ###
