"""add payment intent id in payment table

Revision ID: e1954a548278
Revises: 15bea1ef4374
Create Date: 2026-04-07 11:17:57.703489

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e1954a548278'
down_revision: Union[str, Sequence[str], None] = '15bea1ef4374'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('payments', sa.Column('payment_intent_id', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('payments', 'payment_intent_id')
    # ### end Alembic commands ###
