"""change field name in mechanic data

Revision ID: e761d697986e
Revises: 7d0a432d8b43
Create Date: 2026-03-17 08:45:27.757584

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e761d697986e'
down_revision: Union[str, Sequence[str], None] = '7d0a432d8b43'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('mechanic_data', sa.Column('national_image_id', sa.String(), nullable=True))
    op.add_column('mechanic_data', sa.Column('certificate_image_id', sa.String(), nullable=True))
    op.drop_column('mechanic_data', 'certificate_id')
    op.drop_column('mechanic_data', 'national_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('mechanic_data', sa.Column('national_id', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('mechanic_data', sa.Column('certificate_id', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('mechanic_data', 'certificate_image_id')
    op.drop_column('mechanic_data', 'national_image_id')
    # ### end Alembic commands ###
